In [4]:
#202331175 Rizal Wira Pambudi
import cv2
import numpy as np

In [6]:
#202331175 Rizal Wira Pambudi
citra = cv2.imread("waa.jpg")
cv2.imshow("Kucing", citra)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [40]:
#202331175 Rizal Wira Pambudi
print(citra.shape)
print(citra.dtype)

(338, 270, 3)
uint8


In [11]:
#202331175 Rizal Wira Pambudi
b = citra[:, :, 0]
g = citra[:, :, 1]
r = citra[:, :, 2]

In [13]:
#202331175 Rizal Wira Pambudi
panjang = len(citra)
lebar = len(citra[0])
citra_gray = np.zeros((panjang, lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("Hasil Grayscale", citra_gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [46]:
#202331175 Rizal Wira Pambudi
print(citra)

[[[ 52  56  50]
  [111 115 110]
  [166 170 164]
  ...
  [171 188 205]
  [159 176 194]
  [154 171 189]]

 [[ 98 102  97]
  [154 158 153]
  [180 184 178]
  ...
  [179 196 213]
  [166 183 201]
  [164 181 198]]

 [[164 169 163]
  [183 187 182]
  [182 186 181]
  ...
  [182 199 217]
  [164 181 198]
  [166 183 201]]

 ...

 [[209 217 207]
  [206 214 203]
  [200 208 197]
  ...
  [165 181 194]
  [159 175 188]
  [163 179 193]]

 [[202 213 202]
  [205 215 204]
  [197 207 196]
  ...
  [165 181 192]
  [157 173 184]
  [166 183 194]]

 [[202 213 202]
  [205 215 204]
  [197 207 196]
  ...
  [165 181 192]
  [157 173 184]
  [166 183 194]]]


In [ ]:
#202331175 Rizal Wira Pambudi
panjang = len(citra)
lebar = len(citra[0])

ambang = 128

citra_binary = np.zeros((panjang, lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i, j] >= ambang:
            citra_binary[i, j] = 1
        else:
            citra_binary[i, j] = 0

cv2.imshow("Hasil Binary", citra_binary)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [50]:
#202331175 Rizal Wira Pambudi
print(citra_binary)

[[0. 0. 1. ... 1. 1. 1.]
 [0. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [52]:
#202331175 Rizal Wira Pambudi
print(citra_binary[50,50])

1.0
